// Auto-generated by tools/generate_manifest_and_registry.py
#include "casadi_on_gpu_kernel_registry.h"
#include "dynamics_eval.cuh"
#include "fk_eval.cuh"

namespace casadi_on_gpu {
namespace {
void launch_fkeval(const std::uintptr_t* input_ptrs, const std::uintptr_t* output_ptrs, int blocks, int threads_per_block, cudaStream_t stream, int n_candidates) {
  auto* i0 = reinterpret_cast<const casadi_real*>(input_ptrs[0]);
  auto* i1 = reinterpret_cast<const casadi_real*>(input_ptrs[1]);
  auto* i2 = reinterpret_cast<const casadi_real*>(input_ptrs[2]);
  auto* o0 = reinterpret_cast<casadi_real*>(output_ptrs[0]);
  fkeval_kernel<<<blocks, threads_per_block, 0, stream>>>(i0, i1, i2, o0, n_candidates);
}

void launch_Vnext_reg(const std::uintptr_t* input_ptrs, const std::uintptr_t* output_ptrs, int blocks, int threads_per_block, cudaStream_t stream, int n_candidates) {
  auto* i0 = reinterpret_cast<const casadi_real*>(input_ptrs[0]);
  auto* i1 = reinterpret_cast<const casadi_real*>(input_ptrs[1]);
  auto* i2 = reinterpret_cast<const casadi_real*>(input_ptrs[2]);
  auto* i3 = reinterpret_cast<const casadi_real*>(input_ptrs[3]);
  auto* i4 = reinterpret_cast<const casadi_real*>(input_ptrs[4]);
  auto* o0 = reinterpret_cast<casadi_real*>(output_ptrs[0]);
  Vnext_reg_kernel<<<blocks, threads_per_block, 0, stream>>>(i0, i1, i2, i3, i4, o0, n_candidates);
}

const KernelEntry kRegistry[] = {
  {"fkeval", "fkeval_kernel", 3, 1, {0}, {4, 6, 6}, {6}, launch_fkeval},
  {"Vnext_reg", "Vnext_reg_kernel", 5, 1, {2}, {12, 6, 33, 1, 6}, {12}, launch_Vnext_reg},
};

}  // namespace

const KernelEntry* get_kernel_registry(std::size_t* count) {
  *count = sizeof(kRegistry) / sizeof(kRegistry[0]);
  return kRegistry;
}

}  // namespace casadi_on_gpu
